from examples.pursuit.metrics.PreyCapturesEveryTimestepIntervalMetric import PreyCapturesEveryTimestepIntervalMetric
from examples.pursuit.metrics.TotalPreyCapturesMetric import TotalPreyCapturesMetric
